### ISSUE TITLE
Login functionality broken for some time

### ISSUE THREAD

**Issue by TanishqBakliwal** [ShivanshMishra18/CF-CLI#2]
I used cf-cli about a month back. But when I was trying to login yesterday, it was showing "[*] Already logged in as:". 
There haven't been any changes to the project though. Please check.

**Comment by ShivanshMishra18** [comment]
Hello @TanishqBakliwal, thanks for bringing this forward. 
Codeforces has introduced a new access mechanism to improve security and prevent spamming on the server. It requires the browser to perform a non-trivial amount of computational work before the site can be accessed. 
The earlier version of Codeforces did not rely on this. I need to add scripts to do the computation, which will, most probably, solve the problem.

**Comment by ShivanshMishra18** [comment]
Codeforces has rolled back to the old version. I have tested CF-CLI and all the functions are now working.
